## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

### Making the vectors

In [2]:
import numpy as np

In [3]:
hotmess = np.arange(5,11,1)
hotmess2 = np.arange(15,21,1)

In [5]:
hotouterprod = []
assert len(hotmess) == len(hotmess2)
for i in range(len(hotmess)):
    row = []
    for j in range(len(hotmess2)):
        row.append(hotmess[i]*hotmess2[j])
        
    hotouterprod.append(row)

print('Outer Product:')
hotouterprod

Outer Product:


[[75, 80, 85, 90, 95, 100],
 [90, 96, 102, 108, 114, 120],
 [105, 112, 119, 126, 133, 140],
 [120, 128, 136, 144, 152, 160],
 [135, 144, 153, 162, 171, 180],
 [150, 160, 170, 180, 190, 200]]

Part B

In [11]:
trace_array = []

for i in range(len(hotouterprod)):
    trace_array.append(hotouterprod[i][i])
    
print(trace_array)
print(sum(trace_array))
    

[75, 96, 119, 144, 171, 200]
805


In [6]:
hotmessoutnp = np.outer(hotmess, hotmess2)
print('outer product: ',hotmessoutnp)

outer product:  [[ 75  80  85  90  95 100]
 [ 90  96 102 108 114 120]
 [105 112 119 126 133 140]
 [120 128 136 144 152 160]
 [135 144 153 162 171 180]
 [150 160 170 180 190 200]]


In [9]:
hotmesstrace = np.diagonal(hotmessoutnp)
print('trace: ',hotmesstrace)
print('sum: ',hotmesstrace.sum())

trace:  [ 75  96 119 144 171 200]
sum:  805


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

## Make two matrices

In [39]:
randC = np.random.rand(4,3)*10
randD = np.random.rand(3,4)*10
randC = randC.astype(int)
randD = randD.astype(int)

print(randC)
print(randD)

[[7 3 9]
 [8 6 7]
 [5 1 9]
 [2 0 9]]
[[1 4 0 3]
 [3 2 4 2]
 [4 3 5 1]]


## Use conventional for loop

In [41]:
assert len(randC) == len(randD[0]), 'Incompatible matrix dimensions'

matrix_mult = []

for i in range(len(randC)):
    
    for j in range(len(randD[0])):
        
        for k in range(len(randD)):
            matrix_mult[i][j] += randC[i][k] * randD[k][j]
            
for r in matrix_mult:
    print(r)
    
# for i in range(len(A)): 
  
#     # iterating by coloum by B  
#     for j in range(len(B[0])): 
  
#         # iterating by rows of B 
#         for k in range(len(B)): 
#             result[i][j] += A[i][k] * B[k][j] 
  
# for r in result: 
#     print(r) 
    
# print('Matrix Multiplication Product: \n', matrix_mult)
    


IndexError: list index out of range

## List Comprehension

In [35]:
matrix_mult2 = [[sum(a * b for a, b in zip(randC_row, randD_col))  
                        for randD_col in zip(*randD)] 
                                for randC_row in randC] 

print(matrix_mult2)

[[39, 37, 72, 120], [73, 27, 144, 132], [28, 14, 54, 60], [31, 28, 63, 75]]


## Numpy Operator

In [43]:
print('Dot product using numpy: \n', np.dot(randC,randD))

Dot product using numpy: 
 [[52 61 57 36]
 [54 65 59 43]
 [44 49 49 26]
 [38 35 45 15]]


## Fancy Indexing

In [45]:
print(np.dot(randC,randD)[[0,1]][:,[2,3]])

[[57 36]
 [59 43]]


## Change to zeros

In [48]:
diag = []

for i in range(len(randC)):
    diag.append(np.dot(randC,randD)[i][i])



[52, 65, 49, 15]
